version: "3"
services:
  sqlite:
    container_name: sqlite
    build: .
    command: "bundle exec rails db:create db:migrate"
    volumes:
      - db:/code/db
  sidekiq:
    container_name: sidekiq
    build: .
    command: bundle exec sidekiq -c 5
    environment:
      - REDIS_SERVICE=redis://redis:6379
    volumes:
      - uploads:/code/tmp/uploads
      - db:/code/db
    depends_on:
      - sqlite
      - redis
  web:
    container_name: web
    build: .
    command: sh -c "bundle exec rails assets:precompile && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      - REDIS_SERVICE=redis://redis:6379
    ports:
      - 3000:3000
    volumes:
      - uploads:/code/tmp/uploads
      - db:/code/db
    depends_on:
      - sqlite
      - redis
  redis:
    container_name: redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379/tcp"
volumes:
  uploads:
  db:
