version: "3"
services:
  sqlite:
    container_name: sqlite
    build: .
    command: "bundle exec rails db:create db:migrate"
    volumes:
      - .:/code
  sidekiq:
    container_name: sidekiq
    build: .
    command: bundle exec sidekiq
    environment:
      - REDIS_SERVICE=redis://redis:6379
    volumes:
      - .:/code
    depends_on:
      - sqlite
      - redis
  web:
    container_name: web
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment:
      - REDIS_SERVICE=redis://redis:6379
    ports:
      - 3000:3000
    volumes:
      - .:/code
    depends_on:
      - sqlite
      - redis
  redis:
    container_name: redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379/tcp"
