version: "3"
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  db_setup:
    container_name: db_setup
    build: .
    command: "bundle exec rails db:create db:migrate"
  web:
    container_name: web
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment:
      - WEBPACKER_DEV_SERVER_HOST=assets
    ports:
      - 3000:3000
    volumes:
      - .:/code
    depends_on:
      - assets
      - db_setup
  assets:
      container_name: assets
      build: .
      command: ./bin/webpack-dev-server
      volumes:
        - .:/code
      environment:
        - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      ports:
        - 3035:3035
