development:
  adapter: postgresql
  encoding: unicode
  database: aws_file_upload
  host: db
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: aws_file_upload
  host: db
  pool: 5
  username: postgres
  password: password
